// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcF_xsxY8SXCOEhj0ocyrRF9skYh3ARHE',
    appId: '1:440762465683:web:e403d406a966c1f49e7c66',
    messagingSenderId: '440762465683',
    projectId: 'chat-app-e7426',
    authDomain: 'chat-app-e7426.firebaseapp.com',
    storageBucket: 'chat-app-e7426.firebasestorage.app',
    measurementId: 'G-NPBKDTL7MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6wGFbSphqxPkb7KgiIGNrLmsHdsqHkAQ',
    appId: '1:440762465683:android:662cc6204ba745cb9e7c66',
    messagingSenderId: '440762465683',
    projectId: 'chat-app-e7426',
    storageBucket: 'chat-app-e7426.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlIBjVGsxR8ynDK_vAhnwegeeZ4iXFzAI',
    appId: '1:440762465683:ios:047f0e18a9e0cbf19e7c66',
    messagingSenderId: '440762465683',
    projectId: 'chat-app-e7426',
    storageBucket: 'chat-app-e7426.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlIBjVGsxR8ynDK_vAhnwegeeZ4iXFzAI',
    appId: '1:440762465683:ios:047f0e18a9e0cbf19e7c66',
    messagingSenderId: '440762465683',
    projectId: 'chat-app-e7426',
    storageBucket: 'chat-app-e7426.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcF_xsxY8SXCOEhj0ocyrRF9skYh3ARHE',
    appId: '1:440762465683:web:e7adf59796e9bdc79e7c66',
    messagingSenderId: '440762465683',
    projectId: 'chat-app-e7426',
    authDomain: 'chat-app-e7426.firebaseapp.com',
    storageBucket: 'chat-app-e7426.firebasestorage.app',
    measurementId: 'G-FD0KB0FL2E',
  );
}
